# Server
server.port=8085

# Application Name
spring.application.name=api-gateway

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Eureka Instance
eureka.instance.prefer-ip-address=true

# Gateway Discovery
spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Routes
spring.cloud.gateway.routes[0].id=Orders
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[1].id=Product
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

spring.cloud.gateway.routes[2].id=Users
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[3].id=AuthServer
spring.cloud.gateway.routes[3].uri=http://localhost:9000
spring.cloud.gateway.routes[3].predicates[0]=Path=/oauth2/**,/login,/error

# Default Filter
spring.cloud.gateway.default-filters[0]=AddRequestHeader=X-Gateway, api-gateway

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# Logging
logging.level.com.netflix.discovery=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

springdoc.swagger-ui.urls[0].name=Users
springdoc.swagger-ui.urls[0].url=/users/v3/api-docs

springdoc.swagger-ui.urls[1].name=Product
springdoc.swagger-ui.urls[1].url=/products/v3/api-docs

springdoc.swagger-ui.urls[2].name=Orders
springdoc.swagger-ui.urls[2].url=/orders/v3/api-docs

springdoc.swagger-ui.urls[3].name=Notification
springdoc.swagger-ui.urls[3].url=/notification/v3/api-docs

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true